FROM bitnami/node:12.18.3 AS build

WORKDIR /app
COPY package*.json ./
COPY tsconfig.json .

# RUN npm install  --no-progress --quiet

# RUN yarn add --dev typescript @types/node
# Cleans only leaving code necessary on production
RUN npm ci --only=production

RUN npm install --save-dev typescript @types/react @types/node

COPY ./components ./components
COPY ./pages ./pages
COPY styles.css .

RUN npm run build

# EXPOSE 3000

# # To run in developer mode, change "start" to "dev" in following line
# CMD [ "npm", "run", "start" ]

# FROM node:12-alpine AS build
# #https://medium.com/@michalozogan/how-to-build-the-smallest-docker-typescript-image-a9a84d17e6b4
# WORKDIR /srv
# COPY package*.json /srv/
# RUN npm ci
# COPY tsconfig.json /srv/
# # COPY src /srv/src/
# COPY . /srv/src/

# RUN npm run tsc
# RUN npm ci --production

FROM alpine:3
RUN apk add nodejs --no-cache
WORKDIR /app
COPY --from=build /srv/node_modules /srv/node_modules
COPY --from=build /srv/dist /srv/
CMD node index.js


EXPOSE 3000